on:
  push:
    branches:
      - main

env:
  IMAGE_TAG_MAIN: geminiapi
  IMAGE_TAG_TEST: geminiapitest
  IMAGE_VERSION: v1.0.0

jobs:
  build_job:
    name: Build Docker Image
    runs-on: gemini-win-runner
    steps:
      - name: Clone and checkout
        uses: actions/checkout@v2

      - name: Build Main Image
        run: docker build -t ${{ env.IMAGE_TAG_MAIN }}:$ {{ env.IMAGE_VERSION }} -f Dockerfile .

      - name: Build Test Image
        run: |
          mv .dockerignore .dockerignore.temp
          docker build -t ${{ env.IMAGE_TAG_TEST }}:${{ env.IMAGE_VERSION }} -f DockerfileTest .
          mv dockerignore.temp .dockerignore

  test_job:
    name: Test Docker Image
    runs-on: gemini-win-runner
    environment: development
    steps:
      - name: Unit testing
        run: |
          docker run --rm \
            -e GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} \
            ${{ env. IMAGE_TAG_TEST }}: ${{ env.IMAGE_VERSION }}
          

  deploy_job:
    name: Deploy Docker Image
    runs-on: gemini-win-runner
    environment: development
    steps:
      - name: Remove Running Containers
        run: docker rm -f ${IMAGE_TAG_MAIN} || true

      - name: Deploy Main Image
        run: docker run -d -p 5001:5001 -e GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} --name ${{ env.IMAGE_TAG_MAIN }} ${{ env.IMAGE_TAG_MAIN }}:${{ env.IMAGE_VERSION }}


